# Site settings
baseurl: ""  # empty for meetchashi.github.io (user GitHub Pages site)

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

collections:
  publications:
    output: false
  news:
    output: false
  showcase:
    output: false
  blog:
    output: true
    permalink: /blog/:year/:title/
